// Generated by gencpp from file hello_ros/AddTwoInts.msg
// DO NOT EDIT!


#ifndef HELLO_ROS_MESSAGE_ADDTWOINTS_H
#define HELLO_ROS_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <hello_ros/AddTwoIntsRequest.h>
#include <hello_ros/AddTwoIntsResponse.h>


namespace hello_ros
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace hello_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hello_ros::AddTwoInts > {
  static const char* value()
  {
    return "5993578fda346cb515cdbc700520a62d";
  }

  static const char* value(const ::hello_ros::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::hello_ros::AddTwoInts > {
  static const char* value()
  {
    return "hello_ros/AddTwoInts";
  }

  static const char* value(const ::hello_ros::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::hello_ros::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::hello_ros::AddTwoInts >
template<>
struct MD5Sum< ::hello_ros::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hello_ros::AddTwoInts >::value();
  }
  static const char* value(const ::hello_ros::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hello_ros::AddTwoIntsRequest> should match
// service_traits::DataType< ::hello_ros::AddTwoInts >
template<>
struct DataType< ::hello_ros::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::hello_ros::AddTwoInts >::value();
  }
  static const char* value(const ::hello_ros::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hello_ros::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::hello_ros::AddTwoInts >
template<>
struct MD5Sum< ::hello_ros::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hello_ros::AddTwoInts >::value();
  }
  static const char* value(const ::hello_ros::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hello_ros::AddTwoIntsResponse> should match
// service_traits::DataType< ::hello_ros::AddTwoInts >
template<>
struct DataType< ::hello_ros::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::hello_ros::AddTwoInts >::value();
  }
  static const char* value(const ::hello_ros::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HELLO_ROS_MESSAGE_ADDTWOINTS_H
