// Generated by gencpp from file hello_ros/MyTopic.msg
// DO NOT EDIT!


#ifndef HELLO_ROS_MESSAGE_MYTOPIC_H
#define HELLO_ROS_MESSAGE_MYTOPIC_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hello_ros
{
template <class ContainerAllocator>
struct MyTopic_
{
  typedef MyTopic_<ContainerAllocator> Type;

  MyTopic_()
    : first_name()
    , age(0)
    , score(0)  {
    }
  MyTopic_(const ContainerAllocator& _alloc)
    : first_name(_alloc)
    , age(0)
    , score(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _first_name_type;
  _first_name_type first_name;

   typedef uint8_t _age_type;
  _age_type age;

   typedef uint32_t _score_type;
  _score_type score;





  typedef boost::shared_ptr< ::hello_ros::MyTopic_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hello_ros::MyTopic_<ContainerAllocator> const> ConstPtr;

}; // struct MyTopic_

typedef ::hello_ros::MyTopic_<std::allocator<void> > MyTopic;

typedef boost::shared_ptr< ::hello_ros::MyTopic > MyTopicPtr;
typedef boost::shared_ptr< ::hello_ros::MyTopic const> MyTopicConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hello_ros::MyTopic_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hello_ros::MyTopic_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hello_ros::MyTopic_<ContainerAllocator1> & lhs, const ::hello_ros::MyTopic_<ContainerAllocator2> & rhs)
{
  return lhs.first_name == rhs.first_name &&
    lhs.age == rhs.age &&
    lhs.score == rhs.score;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hello_ros::MyTopic_<ContainerAllocator1> & lhs, const ::hello_ros::MyTopic_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hello_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hello_ros::MyTopic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_ros::MyTopic_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hello_ros::MyTopic_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hello_ros::MyTopic_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_ros::MyTopic_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_ros::MyTopic_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hello_ros::MyTopic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "936b8cbca9e84059fb52d40e0776fdda";
  }

  static const char* value(const ::hello_ros::MyTopic_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x936b8cbca9e84059ULL;
  static const uint64_t static_value2 = 0xfb52d40e0776fddaULL;
};

template<class ContainerAllocator>
struct DataType< ::hello_ros::MyTopic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hello_ros/MyTopic";
  }

  static const char* value(const ::hello_ros::MyTopic_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hello_ros::MyTopic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string first_name\n"
"uint8 age\n"
"uint32 score\n"
;
  }

  static const char* value(const ::hello_ros::MyTopic_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hello_ros::MyTopic_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.first_name);
      stream.next(m.age);
      stream.next(m.score);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MyTopic_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hello_ros::MyTopic_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hello_ros::MyTopic_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "first_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.first_name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "age: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.age);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "score: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.score);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HELLO_ROS_MESSAGE_MYTOPIC_H
