// Generated by gencpp from file hello_ros/TimeWaitAction.msg
// DO NOT EDIT!


#ifndef HELLO_ROS_MESSAGE_TIMEWAITACTION_H
#define HELLO_ROS_MESSAGE_TIMEWAITACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <hello_ros/TimeWaitActionGoal.h>
#include <hello_ros/TimeWaitActionResult.h>
#include <hello_ros/TimeWaitActionFeedback.h>

namespace hello_ros
{
template <class ContainerAllocator>
struct TimeWaitAction_
{
  typedef TimeWaitAction_<ContainerAllocator> Type;

  TimeWaitAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  TimeWaitAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::hello_ros::TimeWaitActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::hello_ros::TimeWaitActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::hello_ros::TimeWaitActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::hello_ros::TimeWaitAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hello_ros::TimeWaitAction_<ContainerAllocator> const> ConstPtr;

}; // struct TimeWaitAction_

typedef ::hello_ros::TimeWaitAction_<std::allocator<void> > TimeWaitAction;

typedef boost::shared_ptr< ::hello_ros::TimeWaitAction > TimeWaitActionPtr;
typedef boost::shared_ptr< ::hello_ros::TimeWaitAction const> TimeWaitActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hello_ros::TimeWaitAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hello_ros::TimeWaitAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hello_ros::TimeWaitAction_<ContainerAllocator1> & lhs, const ::hello_ros::TimeWaitAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hello_ros::TimeWaitAction_<ContainerAllocator1> & lhs, const ::hello_ros::TimeWaitAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hello_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hello_ros::TimeWaitAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_ros::TimeWaitAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hello_ros::TimeWaitAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hello_ros::TimeWaitAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_ros::TimeWaitAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_ros::TimeWaitAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hello_ros::TimeWaitAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9ef8efd1ee50c0a9d2cd133bd31c4f21";
  }

  static const char* value(const ::hello_ros::TimeWaitAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9ef8efd1ee50c0a9ULL;
  static const uint64_t static_value2 = 0xd2cd133bd31c4f21ULL;
};

template<class ContainerAllocator>
struct DataType< ::hello_ros::TimeWaitAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hello_ros/TimeWaitAction";
  }

  static const char* value(const ::hello_ros::TimeWaitAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hello_ros::TimeWaitAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"TimeWaitActionGoal action_goal\n"
"TimeWaitActionResult action_result\n"
"TimeWaitActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: hello_ros/TimeWaitActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"TimeWaitGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: hello_ros/TimeWaitGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Gaol\n"
"float32 time_to_wait # 목표 wait 시간\n"
"\n"
"\n"
"================================================================================\n"
"MSG: hello_ros/TimeWaitActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"TimeWaitResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: hello_ros/TimeWaitResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result\n"
"float32 time_elapsed  # 완료까지 경과 시간\n"
"uint32 updates_sent   # 피드백 횟수\n"
"\n"
"\n"
"================================================================================\n"
"MSG: hello_ros/TimeWaitActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"TimeWaitFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: hello_ros/TimeWaitFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# feedback\n"
"float32 time_remaining # 남은 시간\n"
"float32 time_elapsed # 현재까지 경과 시간\n"
"\n"
"\n"
;
  }

  static const char* value(const ::hello_ros::TimeWaitAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hello_ros::TimeWaitAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimeWaitAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hello_ros::TimeWaitAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hello_ros::TimeWaitAction_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "action_goal: ";
    Printer< ::hello_ros::TimeWaitActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "action_result: ";
    Printer< ::hello_ros::TimeWaitActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "action_feedback: ";
    Printer< ::hello_ros::TimeWaitActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HELLO_ROS_MESSAGE_TIMEWAITACTION_H
