// Generated by gencpp from file hello_ros/TimeWaitActionGoal.msg
// DO NOT EDIT!


#ifndef HELLO_ROS_MESSAGE_TIMEWAITACTIONGOAL_H
#define HELLO_ROS_MESSAGE_TIMEWAITACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <hello_ros/TimeWaitGoal.h>

namespace hello_ros
{
template <class ContainerAllocator>
struct TimeWaitActionGoal_
{
  typedef TimeWaitActionGoal_<ContainerAllocator> Type;

  TimeWaitActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  TimeWaitActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::hello_ros::TimeWaitGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::hello_ros::TimeWaitActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hello_ros::TimeWaitActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct TimeWaitActionGoal_

typedef ::hello_ros::TimeWaitActionGoal_<std::allocator<void> > TimeWaitActionGoal;

typedef boost::shared_ptr< ::hello_ros::TimeWaitActionGoal > TimeWaitActionGoalPtr;
typedef boost::shared_ptr< ::hello_ros::TimeWaitActionGoal const> TimeWaitActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hello_ros::TimeWaitActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hello_ros::TimeWaitActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hello_ros::TimeWaitActionGoal_<ContainerAllocator1> & lhs, const ::hello_ros::TimeWaitActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hello_ros::TimeWaitActionGoal_<ContainerAllocator1> & lhs, const ::hello_ros::TimeWaitActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hello_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hello_ros::TimeWaitActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_ros::TimeWaitActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hello_ros::TimeWaitActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hello_ros::TimeWaitActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_ros::TimeWaitActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_ros::TimeWaitActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hello_ros::TimeWaitActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cfe98d276e809ee2bd1ac65a2378667d";
  }

  static const char* value(const ::hello_ros::TimeWaitActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcfe98d276e809ee2ULL;
  static const uint64_t static_value2 = 0xbd1ac65a2378667dULL;
};

template<class ContainerAllocator>
struct DataType< ::hello_ros::TimeWaitActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hello_ros/TimeWaitActionGoal";
  }

  static const char* value(const ::hello_ros::TimeWaitActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hello_ros::TimeWaitActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"TimeWaitGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: hello_ros/TimeWaitGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Gaol\n"
"float32 time_to_wait # 목표 wait 시간\n"
"\n"
;
  }

  static const char* value(const ::hello_ros::TimeWaitActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hello_ros::TimeWaitActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimeWaitActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hello_ros::TimeWaitActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hello_ros::TimeWaitActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::hello_ros::TimeWaitGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HELLO_ROS_MESSAGE_TIMEWAITACTIONGOAL_H
