// Generated by gencpp from file hello_ros/TimeWaitResult.msg
// DO NOT EDIT!


#ifndef HELLO_ROS_MESSAGE_TIMEWAITRESULT_H
#define HELLO_ROS_MESSAGE_TIMEWAITRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hello_ros
{
template <class ContainerAllocator>
struct TimeWaitResult_
{
  typedef TimeWaitResult_<ContainerAllocator> Type;

  TimeWaitResult_()
    : time_elapsed(0.0)
    , updates_sent(0)  {
    }
  TimeWaitResult_(const ContainerAllocator& _alloc)
    : time_elapsed(0.0)
    , updates_sent(0)  {
  (void)_alloc;
    }



   typedef float _time_elapsed_type;
  _time_elapsed_type time_elapsed;

   typedef uint32_t _updates_sent_type;
  _updates_sent_type updates_sent;





  typedef boost::shared_ptr< ::hello_ros::TimeWaitResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hello_ros::TimeWaitResult_<ContainerAllocator> const> ConstPtr;

}; // struct TimeWaitResult_

typedef ::hello_ros::TimeWaitResult_<std::allocator<void> > TimeWaitResult;

typedef boost::shared_ptr< ::hello_ros::TimeWaitResult > TimeWaitResultPtr;
typedef boost::shared_ptr< ::hello_ros::TimeWaitResult const> TimeWaitResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hello_ros::TimeWaitResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hello_ros::TimeWaitResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hello_ros::TimeWaitResult_<ContainerAllocator1> & lhs, const ::hello_ros::TimeWaitResult_<ContainerAllocator2> & rhs)
{
  return lhs.time_elapsed == rhs.time_elapsed &&
    lhs.updates_sent == rhs.updates_sent;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hello_ros::TimeWaitResult_<ContainerAllocator1> & lhs, const ::hello_ros::TimeWaitResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hello_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hello_ros::TimeWaitResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_ros::TimeWaitResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hello_ros::TimeWaitResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hello_ros::TimeWaitResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_ros::TimeWaitResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_ros::TimeWaitResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hello_ros::TimeWaitResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b19b7ee88bc8056c043443e2ebfc99f2";
  }

  static const char* value(const ::hello_ros::TimeWaitResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb19b7ee88bc8056cULL;
  static const uint64_t static_value2 = 0x043443e2ebfc99f2ULL;
};

template<class ContainerAllocator>
struct DataType< ::hello_ros::TimeWaitResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hello_ros/TimeWaitResult";
  }

  static const char* value(const ::hello_ros::TimeWaitResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hello_ros::TimeWaitResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result\n"
"float32 time_elapsed  # 완료까지 경과 시간\n"
"uint32 updates_sent   # 피드백 횟수\n"
"\n"
;
  }

  static const char* value(const ::hello_ros::TimeWaitResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hello_ros::TimeWaitResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time_elapsed);
      stream.next(m.updates_sent);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimeWaitResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hello_ros::TimeWaitResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hello_ros::TimeWaitResult_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "time_elapsed: ";
    Printer<float>::stream(s, indent + "  ", v.time_elapsed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "updates_sent: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.updates_sent);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HELLO_ROS_MESSAGE_TIMEWAITRESULT_H
