(cl:defpackage hello_ros-msg
  (:use )
  (:export
   "<MYTOPIC>"
   "MYTOPIC"
   "<TIMEWAITACTION>"
   "TIMEWAITACTION"
   "<TIMEWAITACTIONFEEDBACK>"
   "TIMEWAITACTIONFEEDBACK"
   "<TIMEWAITACTIONGOAL>"
   "TIMEWAITACTIONGOAL"
   "<TIMEWAITACTIONRESULT>"
   "TIMEWAITACTIONRESULT"
   "<TIMEWAITFEEDBACK>"
   "TIMEWAITFEEDBACK"
   "<TIMEWAITGOAL>"
   "TIMEWAITGOAL"
   "<TIMEWAITRESULT>"
   "TIMEWAITRESULT"
  ))

