; Auto-generated. Do not edit!


(cl:in-package hello_ros-msg)


;//! \htmlinclude TimeWaitResult.msg.html

(cl:defclass <TimeWaitResult> (roslisp-msg-protocol:ros-message)
  ((time_elapsed
    :reader time_elapsed
    :initarg :time_elapsed
    :type cl:float
    :initform 0.0)
   (updates_sent
    :reader updates_sent
    :initarg :updates_sent
    :type cl:integer
    :initform 0))
)

(cl:defclass TimeWaitResult (<TimeWaitResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TimeWaitResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TimeWaitResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hello_ros-msg:<TimeWaitResult> is deprecated: use hello_ros-msg:TimeWaitResult instead.")))

(cl:ensure-generic-function 'time_elapsed-val :lambda-list '(m))
(cl:defmethod time_elapsed-val ((m <TimeWaitResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hello_ros-msg:time_elapsed-val is deprecated.  Use hello_ros-msg:time_elapsed instead.")
  (time_elapsed m))

(cl:ensure-generic-function 'updates_sent-val :lambda-list '(m))
(cl:defmethod updates_sent-val ((m <TimeWaitResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hello_ros-msg:updates_sent-val is deprecated.  Use hello_ros-msg:updates_sent instead.")
  (updates_sent m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TimeWaitResult>) ostream)
  "Serializes a message object of type '<TimeWaitResult>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'time_elapsed))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'updates_sent)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'updates_sent)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'updates_sent)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'updates_sent)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TimeWaitResult>) istream)
  "Deserializes a message object of type '<TimeWaitResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'time_elapsed) (roslisp-utils:decode-single-float-bits bits)))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'updates_sent)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'updates_sent)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'updates_sent)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'updates_sent)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TimeWaitResult>)))
  "Returns string type for a message object of type '<TimeWaitResult>"
  "hello_ros/TimeWaitResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TimeWaitResult)))
  "Returns string type for a message object of type 'TimeWaitResult"
  "hello_ros/TimeWaitResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TimeWaitResult>)))
  "Returns md5sum for a message object of type '<TimeWaitResult>"
  "b19b7ee88bc8056c043443e2ebfc99f2")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TimeWaitResult)))
  "Returns md5sum for a message object of type 'TimeWaitResult"
  "b19b7ee88bc8056c043443e2ebfc99f2")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TimeWaitResult>)))
  "Returns full string definition for message of type '<TimeWaitResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%float32 time_elapsed  # 완료까지 경과 시간~%uint32 updates_sent   # 피드백 횟수~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TimeWaitResult)))
  "Returns full string definition for message of type 'TimeWaitResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%float32 time_elapsed  # 완료까지 경과 시간~%uint32 updates_sent   # 피드백 횟수~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TimeWaitResult>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TimeWaitResult>))
  "Converts a ROS message object to a list"
  (cl:list 'TimeWaitResult
    (cl:cons ':time_elapsed (time_elapsed msg))
    (cl:cons ':updates_sent (updates_sent msg))
))
