; Auto-generated. Do not edit!


(cl:in-package hello_ros-msg)


;//! \htmlinclude TimeWaitFeedback.msg.html

(cl:defclass <TimeWaitFeedback> (roslisp-msg-protocol:ros-message)
  ((time_remaining
    :reader time_remaining
    :initarg :time_remaining
    :type cl:float
    :initform 0.0)
   (time_elapsed
    :reader time_elapsed
    :initarg :time_elapsed
    :type cl:float
    :initform 0.0))
)

(cl:defclass TimeWaitFeedback (<TimeWaitFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TimeWaitFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TimeWaitFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hello_ros-msg:<TimeWaitFeedback> is deprecated: use hello_ros-msg:TimeWaitFeedback instead.")))

(cl:ensure-generic-function 'time_remaining-val :lambda-list '(m))
(cl:defmethod time_remaining-val ((m <TimeWaitFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hello_ros-msg:time_remaining-val is deprecated.  Use hello_ros-msg:time_remaining instead.")
  (time_remaining m))

(cl:ensure-generic-function 'time_elapsed-val :lambda-list '(m))
(cl:defmethod time_elapsed-val ((m <TimeWaitFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hello_ros-msg:time_elapsed-val is deprecated.  Use hello_ros-msg:time_elapsed instead.")
  (time_elapsed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TimeWaitFeedback>) ostream)
  "Serializes a message object of type '<TimeWaitFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'time_remaining))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'time_elapsed))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TimeWaitFeedback>) istream)
  "Deserializes a message object of type '<TimeWaitFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'time_remaining) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'time_elapsed) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TimeWaitFeedback>)))
  "Returns string type for a message object of type '<TimeWaitFeedback>"
  "hello_ros/TimeWaitFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TimeWaitFeedback)))
  "Returns string type for a message object of type 'TimeWaitFeedback"
  "hello_ros/TimeWaitFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TimeWaitFeedback>)))
  "Returns md5sum for a message object of type '<TimeWaitFeedback>"
  "acdbae04adc7654db9c9b1a52d9ede06")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TimeWaitFeedback)))
  "Returns md5sum for a message object of type 'TimeWaitFeedback"
  "acdbae04adc7654db9c9b1a52d9ede06")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TimeWaitFeedback>)))
  "Returns full string definition for message of type '<TimeWaitFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%float32 time_remaining # 남은 시간~%float32 time_elapsed # 현재까지 경과 시간~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TimeWaitFeedback)))
  "Returns full string definition for message of type 'TimeWaitFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%float32 time_remaining # 남은 시간~%float32 time_elapsed # 현재까지 경과 시간~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TimeWaitFeedback>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TimeWaitFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'TimeWaitFeedback
    (cl:cons ':time_remaining (time_remaining msg))
    (cl:cons ':time_elapsed (time_elapsed msg))
))
