; Auto-generated. Do not edit!


(cl:in-package hello_ros-msg)


;//! \htmlinclude TimeWaitGoal.msg.html

(cl:defclass <TimeWaitGoal> (roslisp-msg-protocol:ros-message)
  ((time_to_wait
    :reader time_to_wait
    :initarg :time_to_wait
    :type cl:float
    :initform 0.0))
)

(cl:defclass TimeWaitGoal (<TimeWaitGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TimeWaitGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TimeWaitGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hello_ros-msg:<TimeWaitGoal> is deprecated: use hello_ros-msg:TimeWaitGoal instead.")))

(cl:ensure-generic-function 'time_to_wait-val :lambda-list '(m))
(cl:defmethod time_to_wait-val ((m <TimeWaitGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hello_ros-msg:time_to_wait-val is deprecated.  Use hello_ros-msg:time_to_wait instead.")
  (time_to_wait m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TimeWaitGoal>) ostream)
  "Serializes a message object of type '<TimeWaitGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'time_to_wait))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TimeWaitGoal>) istream)
  "Deserializes a message object of type '<TimeWaitGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'time_to_wait) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TimeWaitGoal>)))
  "Returns string type for a message object of type '<TimeWaitGoal>"
  "hello_ros/TimeWaitGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TimeWaitGoal)))
  "Returns string type for a message object of type 'TimeWaitGoal"
  "hello_ros/TimeWaitGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TimeWaitGoal>)))
  "Returns md5sum for a message object of type '<TimeWaitGoal>"
  "490f5a78b6ea9351e88beac27668bc8c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TimeWaitGoal)))
  "Returns md5sum for a message object of type 'TimeWaitGoal"
  "490f5a78b6ea9351e88beac27668bc8c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TimeWaitGoal>)))
  "Returns full string definition for message of type '<TimeWaitGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Gaol~%float32 time_to_wait # 목표 wait 시간~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TimeWaitGoal)))
  "Returns full string definition for message of type 'TimeWaitGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Gaol~%float32 time_to_wait # 목표 wait 시간~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TimeWaitGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TimeWaitGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'TimeWaitGoal
    (cl:cons ':time_to_wait (time_to_wait msg))
))
