// Auto-generated. Do not edit!

// (in-package hello_ros.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class TimeWaitResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.time_elapsed = null;
      this.updates_sent = null;
    }
    else {
      if (initObj.hasOwnProperty('time_elapsed')) {
        this.time_elapsed = initObj.time_elapsed
      }
      else {
        this.time_elapsed = 0.0;
      }
      if (initObj.hasOwnProperty('updates_sent')) {
        this.updates_sent = initObj.updates_sent
      }
      else {
        this.updates_sent = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type TimeWaitResult
    // Serialize message field [time_elapsed]
    bufferOffset = _serializer.float32(obj.time_elapsed, buffer, bufferOffset);
    // Serialize message field [updates_sent]
    bufferOffset = _serializer.uint32(obj.updates_sent, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type TimeWaitResult
    let len;
    let data = new TimeWaitResult(null);
    // Deserialize message field [time_elapsed]
    data.time_elapsed = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [updates_sent]
    data.updates_sent = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'hello_ros/TimeWaitResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'b19b7ee88bc8056c043443e2ebfc99f2';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Result
    float32 time_elapsed  # 완료까지 경과 시간
    uint32 updates_sent   # 피드백 횟수
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new TimeWaitResult(null);
    if (msg.time_elapsed !== undefined) {
      resolved.time_elapsed = msg.time_elapsed;
    }
    else {
      resolved.time_elapsed = 0.0
    }

    if (msg.updates_sent !== undefined) {
      resolved.updates_sent = msg.updates_sent;
    }
    else {
      resolved.updates_sent = 0
    }

    return resolved;
    }
};

module.exports = TimeWaitResult;
